### ISSUE TITLE
有个小疑问

### ISSUE THREAD

**Issue by todoXu** [oldjun/yazi-json#1]
析构为啥不实现？
Json::~Json()
{
   clear();
}

这样不就好了

**Comment by oldjun** [comment]
因为我考虑性能方面的因素，copy采用的是浅拷贝。如果在析构里调用clear，会导致parser返回的临时Json对象自动销毁，动态分配的内存会被释放，这个跟我们预期的结果不一样。所以clear不能隐式调用，需要自己动手去clear。这个目前我还没想到更好的方案，只能这样先。
