### ISSUE TITLE
parse_array存在的问题

### ISSUE THREAD

**Issue by Jack20-7** [oldjun/yazi-json#3]
Json Parser::parse_array()
{
    Json arr(Json::json_array);
    char ch = get_next_token();
    if (ch == ']')
    {
        return arr;
    }
    m_idx--;
    while (true)
    {
        arr.append(parse());
        ch = get_next_token();
        if (ch == ']')
        {
            break;
        }
        if (ch != ',')
        {
            throw std::logic_error("expected ',' in array");
        }
        m_idx++;
    }
    return arr;
}

在每一次while循环结束之后，会m_idx++.但是在++之前，就处于m_idx就处于逗号后面一个位置，这里再++的话，那么就处于逗号后面的第二个位置，这个时候再去调用parse，就会出现异常，因为parse里面通过get_next_token得到的是第二个位置的字符

**Comment by oldjun** [comment]
有测试案例吗？

**Comment by Jack20-7** [comment]
我知道问题出现在哪里了，你这里要求array中的每一个元素的 逗号之后需要有一个空格进行间隔，如果没有空格就会报错。后面的这个++就是用来跳过空格的。我感觉没有必要++，因为下一次循环也是调用的是parse，而parse中取第一个字符是通过get_next_token来取的，这个空格会被自动跳过

**Comment by Jack20-7** [comment]
测试用例的话，你可以使用你上面的那个main,.json进行测试

**Comment by oldjun** [comment]
谢谢你提供的线索，已经修复这个bug了。
